version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${DATABASE_HOST}
            port: 5432
            user: ${DATABASE_USER}
            password: ${DATABASE_PASS}
            migrations: true

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
